/**
 * Up to 10 server slots.
 * Copy this file to servers.js and fill in what you use.
 *
 * platform: 'xbox' | 'playstation' | 'steam' | 'pc' | 'reforger'
 * game:     'dayz' | 'reforger'
 * mode:     'pve' | 'pvp' | 'other'
 *
 * Leave unused slots out, or set enabled: false.
 */
module.exports = [
  {
    id: 'server-1',
    name: 'Server 1 Name',
    platform: 'xbox',
    game: 'dayz',
    mode: 'pve',
    map: 'chernarus',
    enabled: false,
    nitradoServiceId: null,
    killfeedChannelId: null,
    connectionsChannelId: null,
    expansionMarketPath: null,
    shopCatalog: 'default',
  },
  {
    id: 'server-2',
    name: 'Server 2 Name',
    platform: 'xbox',
    game: 'dayz',
    mode: 'pve',
    map: 'livonia',
    enabled: false,
    nitradoServiceId: null,
    killfeedChannelId: null,
    connectionsChannelId: null,
    expansionMarketPath: null,
    shopCatalog: 'default',
  },
  {
    id: 'server-3',
    name: 'Server 3 Name',
    platform: 'xbox',
    game: 'dayz',
    mode: 'pve',
    map: 'sakhal',
    enabled: false,
    nitradoServiceId: null,
    killfeedChannelId: null,
    connectionsChannelId: null,
    expansionMarketPath: null,
    shopCatalog: 'default',
  },
  {
    id: 'server-4',
    name: 'Server 4 Name',
    platform: 'xbox',
    game: 'dayz',
    mode: 'pvp',
    map: 'chernarus',
    enabled: false,
    nitradoServiceId: null,
    killfeedChannelId: null,
    connectionsChannelId: null,
    expansionMarketPath: null,
    shopCatalog: 'default',
  },
  {
    id: 'server-5',
    name: 'Server 5 Name',
    platform: 'xbox',
    game: 'dayz',
    mode: 'pvp',
    map: 'chernarus',
    enabled: false,
    nitradoServiceId: null,
    killfeedChannelId: null,
    connectionsChannelId: null,
    expansionMarketPath: null,
    shopCatalog: 'default',
  },
  {
    id: 'server-6',
    name: 'Server 6 Name',
    platform: 'steam',
    game: 'dayz',
    mode: 'pve',
    map: 'chernarus',
    enabled: false,
    nitradoServiceId: null,
    killfeedChannelId: null,
    connectionsChannelId: null,
    expansionMarketPath: null,
    shopCatalog: 'default',
  },
  {
    id: 'server-7',
    name: 'Server 7 Name',
    platform: 'steam',
    game: 'dayz',
    mode: 'other',
    map: 'chernarus',
    enabled: false,
    nitradoServiceId: null,
    killfeedChannelId: null,
    connectionsChannelId: null,
    expansionMarketPath: null,
    shopCatalog: 'default',
  },
  {
    id: 'server-8',
    name: 'Server 8 Name',
    platform: 'playstation',
    game: 'dayz',
    mode: 'pve',
    map: 'chernarus',
    enabled: false,
    nitradoServiceId: null,
    killfeedChannelId: null,
    connectionsChannelId: null,
    expansionMarketPath: null,
    shopCatalog: 'default',
  },
  {
    id: 'server-9',
    name: 'Server 9 Name',
    platform: 'reforger',
    game: 'reforger',
    mode: 'pvp',
    map: 'everon',
    enabled: false,
    nitradoServiceId: null,
    killfeedChannelId: null,
    connectionsChannelId: null,
    expansionMarketPath: null,
    shopCatalog: 'default',
  },
  {
    id: 'server-10',
    name: 'Server 10 Name',
    platform: 'pc',
    game: 'dayz',
    mode: 'pve',
    map: 'chernarus',
    enabled: false,
    nitradoServiceId: null,
    killfeedChannelId: null,
    connectionsChannelId: null,
    expansionMarketPath: null,
    shopCatalog: 'default',
  },
];
